name: CI
on: 
  push:
    branches: 
    - master
  pull_request:
    branches: 
    - master

jobs:

  "sanity-Tests":
    runs-on: macOS-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Install swiftformat
      run: brew install swiftformat
    - name: Run sanity
      run: ./scripts/sanity.sh .

  "tuxOS-Tests":
    runs-on: ubuntu-latest
    strategy:
      matrix:
        images:
        - swift:5.1
        - swift:5.2
        - swiftlang/swift:nightly-5.3-bionic
        - swiftlang/swift:nightly-amazonlinux2
    container:
      image: ${{ matrix.images }}
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Test
      run: swift test --enable-code-coverage --enable-test-discovery
    - name: Convert coverage files
      run: llvm-cov export -format="lcov" .build/debug/swift-base64-kitPackageTests.xctest -instr-profile .build/debug/codecov/default.profdata > info.lcov
    - name: Install curl
      if: matrix.images != 'swiftlang/swift:nightly-amazonlinux2'
      run: apt-get update && apt-get install -y curl # required by the codecov action.
    - name: Upload to codecov.io
      uses: codecov/codecov-action@v1
      with:
        file: info.lcov

  "tuxOS-Performance-Tests":
    runs-on: ubuntu-latest
    strategy:
      matrix:
        images:
        - swift:5.1
        - swift:5.2
        - swiftlang/swift:nightly-5.3-bionic
        - swiftlang/swift:nightly-amazonlinux2
    container:
      image: ${{ matrix.images }}
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Build
      run: swift build -c release
    - name: Run test
      run: .build/release/Base64KitPerformanceTest

  "macOS-Tests":
    runs-on: macOS-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Show all Xcode versions
      run: ls -an /Applications/ | grep Xcode*
    - name: Change Xcode command line tools
      run: sudo xcode-select -s /Applications/Xcode_11.2.app/Contents/Developer
    - name: SPM Build
      run: swift build
    - name: SPM Tests
      run: swift test --parallel -Xswiftc -DDEBUG
    - name: Xcode Tests
      run: |
        swift package generate-xcodeproj
        xcodebuild -quiet -parallel-testing-enabled YES -scheme swift-base64-kit-Package -enableCodeCoverage YES build test
    - name: Codecov
      run: bash <(curl -s https://codecov.io/bash) -t ${{secrets.CODECOV_TOKEN}} -f *.coverage.txt

  "macOS-Performance-Tests":
    runs-on: macOS-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Build
      run: swift build -c release
    - name: Run test
      run: .build/release/Base64KitPerformanceTest
