name: CI
on: 
  push:
    branches: 
    - master
  pull_request:
    branches: 
    - master

jobs:

  "tuxOS-Tests":
    runs-on: ubuntu-latest
    strategy:
      matrix:
        tag: ['5.1']
    container:
      image: swift:${{ matrix.tag }}
      volumes:
      - $GITHUB_WORKSPACE:/src
      options: --workdir /src
    steps:
    - name: Checkout
      uses: actions/checkout@v1
      with:
        fetch-depth: 1
    - name: Test
      run: swift test --enable-code-coverage --enable-test-discovery
    - name: Convert coverage files
      run: llvm-cov export -format="lcov" .build/debug/swift-base64PackageTests.xctest -instr-profile .build/debug/codecov/default.profdata > info.lcov
    - name: Upload to codecov.io
      uses: codecov/codecov-action@v1.0.3
      with:
        token: ${{secrets.CODECOV_TOKEN}}
        flags: base64,unittests
        file: info.lcov

  "tuxOS-Performance-Tests":
    runs-on: ubuntu-latest
    strategy:
      matrix:
        tag: ['5.1']
    container:
      image: swift:${{ matrix.tag }}
      volumes:
      - $GITHUB_WORKSPACE:/src
      options: --workdir /src
    steps:
    - name: Checkout
      uses: actions/checkout@v1
      with:
        fetch-depth: 1
    - name: Build
      run: swift build -c release
    - name: Run test
      run: .build/release/Base64PerformanceTest

  "macOS-Tests":
    runs-on: macOS-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v1
      with:
        fetch-depth: 1
    - name: Show all Xcode versions
      run: ls -an /Applications/ | grep Xcode*
    - name: Change Xcode command line tools
      run: sudo xcode-select -s /Applications/Xcode_11.2.app/Contents/Developer
    - name: SPM Build
      run: swift build
    - name: SPM Tests
      run: swift test --parallel -Xswiftc -DDEBUG
    - name: Xcode Tests
      run: |
        swift package generate-xcodeproj
        xcodebuild -quiet -parallel-testing-enabled YES -scheme swift-base64-Package -enableCodeCoverage YES build test
    - name: Codecov
      run: bash <(curl -s https://codecov.io/bash) -t ${{secrets.CODECOV_TOKEN}} -F base64,unittests -f *.coverage.txt

  "macOS-Performance-Tests":
    runs-on: macOS-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v1
      with:
        fetch-depth: 1
    - name: Build
      run: swift build -c release
    - name: Run test
      run: .build/release/Base64PerformanceTest
