name: CI
on: 
  push:
    branches: 
    - main
  pull_request:
    branches: 
    - main

jobs:

  "validity-Tests":
    runs-on: macOS-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Install swiftformat
      run: brew install swiftformat
    - name: Run validity
      run: ./scripts/validity.sh .

  "tuxOS-Tests":
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        images:
        - swift:5.8
        - swift:5.9
        - swift:5.10
        - swiftlang/swift:nightly-jammy
    container:
      image: ${{ matrix.images }}
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Test
      run: swift test --enable-code-coverage
    - name: Convert coverage files
      run: llvm-cov export -format="lcov" .build/debug/swift-extras-base64PackageTests.xctest -instr-profile .build/debug/codecov/default.profdata > info.lcov
    - name: Upload to codecov.io
      uses: codecov/codecov-action@v4
      with:
        file: info.lcov

  "macOS-Tests":
    runs-on: macOS-14
    strategy:
      fail-fast: false
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: SPM Tests
      run: swift test --parallel --enable-code-coverage -Xswiftc -DDEBUG
    - name: Convert coverage files
      run: xcrun llvm-cov export -format="lcov" .build/debug/swift-extras-base64PackageTests.xctest/Contents/MacOS/swift-extras-base64PackageTests -instr-profile .build/debug/codecov/default.profdata > info.lcov
    - name: Upload to codecov.io
      uses: codecov/codecov-action@v4
      with:
        file: info.lcov
